# Токен телеграм бота
TG_TOKEN: TOKEN

SQLALCHEMY_DB_NAME: tgbot
SQLALCHEMY_IP: localhost
SQLALCHEMY_PORT: 5432
SQLALCHEMY_USER: postgres
SQLALCHEMY_PASSWORD: 1

ADMIN_IDS: 123 321

OPENAI_API_KEY: sk-proj-
OPENAI_MODEL: gpt-4o-mini
OPENAI_ADMIN_MODEL: gpt-4o
OPENAI_ADMIN_TOKEN_LIMIT:
QWEN_API_KEY: sk-
QWEN_MODEL: qwen-max
QWEN_IMAGE_MODEL: qwen-vl-plus
ANTHROPIC_API_KEY: sk-ant-api03-
ANTHROPIC_MODEL: claude-3-7-sonnet-20250219

GEN_VIDEO_API_KEY: YOUR_API_KEY
GEN_VIDEO_ASPECT_RATIO: 16:9
GEN_VIDEO_DURATION: 10

GEN_IMAGE_MODEL: dall-e-3
GEN_IMAGE_SIZE: 1024x1024
GEN_IMAGE_QUALITY: standard


CKASSA_MAIN_PROPERTY: ЛИЦЕВОЙ_СЧЕТ
CKASSA_BASE_URL: https://demo-api2.ckassa.ru/api-shop
ApiLoginAuthorization: 1a4c0d33-010c-4365-9c65-4c7f9bb415d5
ApiAuthorization: 6a7abaad-2147-4646-b91a-435b5d97527b
servCode: 1000-13864-2
CKASSA_WEBHOOKS_URL: https://WEBSITE.COM/pay/ckassa
CKASSA_WEBHOOKS_PORT: 80

TIMEZONE: Europe/Moscow

REDIS_HOST: 6379
REDIS_DB: 0