# Токен телеграм бота
TG_TOKEN: TOKEN

SQLALCHEMY_DB_NAME: tgbot
SQLALCHEMY_IP: localhost
SQLALCHEMY_PORT: 5432
SQLALCHEMY_USER: postgres
SQLALCHEMY_PASSWORD: 1

ADMIN_IDS: 123 321

OPENAI_API_KEY: sk-proj-
OPENAI_MODEL: gpt-4o-mini
OPENAI_ADMIN_MODEL: gpt-4o
OPENAI_ADMIN_TOKEN_LIMIT: 99999

QWEN_API_KEY: sk-
QWEN_MODEL: qwen-max

CKASSA_BASE_URL: https://demo-api2.ckassa.ru/api-shop
CKASSA_SHOP_TOKEN: 1a4c0d33-010c-4365-9c65-4c7f9bb415d5
CKASSA_SEC_KEY: 6a7abaad-2147-4646-b91a-435b5d97527b
CKASSA_SERVICE_CODE: 1000-13864-2
CKASSA_WEBHOOKS_URL: https://WEBSITE.COM/pay/ckassa
CKASSA_WEBHOOKS_PORT: 80

TIMEZONE: Europe/Moscow

REDIS_HOST: 6379
REDIS_DB: 0